# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20170219_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=5, verbose_name='Nombre'),
        ),
    ]
