# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-22 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20170227_0204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto'},
        ),
        migrations.AlterModelOptions(
            name='productamount',
            options={'verbose_name': 'Cantidad de Producto'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Talla'},
        ),
    ]
