# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-22 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170219_2344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario'},
        ),
    ]
