# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-22 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Descripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='titulo')),
                ('contenido', models.TextField(default='', verbose_name='Contenido')),
            ],
        ),
    ]
