# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-22 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descripcion',
            options={'verbose_name_plural': 'Descripciones'},
        ),
        migrations.AddField(
            model_name='descripcion',
            name='orden',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
    ]
