# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merceria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
            ],
        ),
    ]
