# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20170227_0204'),
        ('inventario', '0002_merceria_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('tipo', models.CharField(choices=[('T', 'Talla'), ('P', 'Publicidad')], default='T', max_length=1, verbose_name='Tipo')),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Size', verbose_name='Talla')),
            ],
        ),
    ]
