# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_etiqueta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
            ],
        ),
    ]
