# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-22 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_tela'),
    ]

    operations = [
        migrations.AddField(
            model_name='tela',
            name='image',
            field=models.ImageField(blank=True, upload_to='telas/%Y/%m/%d'),
        ),
    ]
